version: "3.9"

volumes:
  quiz_mysql_db:
    driver: local

networks:
  quiz_development_network:
    name: quiz_development_network
    external: true

services:
  mysql-db:
    image: mysql:latest
    container_name: quiz-mysql
    ports:
      - "3336:3306"
    volumes:
      - quiz_mysql_db:/var/lib/mysql
      - ./init:/quiz-docker-entrypoint-initdb.d
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_quiz_password
      MYSQL_DATABASE: quiz_reward
      MYSQL_USER: quiz_user
      MYSQL_PASSWORD: quiz_password
    networks:
      - quiz_development_network

  proxy-server:
    image: jwilder/nginx-proxy
    container_name: quiz-proxy-server
    ports:
      - "81:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - quiz_development_network

  redis:
    image: redis
    container_name: quiz-redis-server
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 6380:${REDIS_PORT}
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
    networks:
      - quiz_development_network
